runtime: nodejs18

instance_class: F1

env_variables:
  NODE_ENV: 'production'

handlers:
  # Servir arquivos estáticos (JS, CSS, etc.)
  - url: /(.*\.(js|css|ico|png|jpg|jpeg|svg|woff|woff2|ttf|eot|json|txt))
    static_files: dist/frontend/browser/\1
    upload: dist/frontend/browser/.*\.(js|css|ico|png|jpg|jpeg|svg|woff|woff2|ttf|eot|json|txt)

  # Redirecionar todas as outras rotas para index.html
  - url: /.*
    static_files: dist/frontend/browser/index.html
    upload: dist/frontend/browser/index.html

service: angular-app
